# Generated by Django 4.2.2 on 2023-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
