# Generated by Django 4.2.2 on 2024-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseadmin',
            name='roles',
        ),
        migrations.AddField(
            model_name='enterpriseadmin',
            name='roles',
            field=models.ManyToManyField(to='entreprise.role'),
        ),
    ]
