# Generated by Django 4.2.2 on 2023-11-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorname', models.CharField(default='', max_length=255)),
                ('sectordesciption', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sectors',
            field=models.ManyToManyField(default=1, to='entreprise.economicsector'),
        ),
    ]
