# Generated by Django 4.2.2 on 2023-12-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='director_fullname',
            new_name='director_lastname',
        ),
    ]
