# Generated by Django 4.2.2 on 2023-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_rename_director_fullname_enterprise_director_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='director_firstname',
            field=models.CharField(default='String', max_length=255),
        ),
    ]
