# Generated by Django 4.2.2 on 2023-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_rename_entreprise_enterprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='description',
            field=models.CharField(default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='director_firstname',
            field=models.CharField(default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='director_lastname',
            field=models.CharField(default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='dirrector_card_id',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='dirrector_card_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('CNI', 'CNI')], default='CNI', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='ifu',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='rccm',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='request_to_use',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
