# Generated by Django 4.2.2 on 2023-07-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprise', '0003_alter_enterprise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseadmin',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
