# Generated by Django 4.2.2 on 2023-12-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_remove_enterprise_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='sectors',
            field=models.ManyToManyField(default=1, to='entreprise.economicsector'),
        ),
    ]
