# Generated by Django 4.2.2 on 2023-12-16 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_enterprise_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
