# Generated by Django 4.2.2 on 2023-12-21 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_employee_date_created_at_employee_date_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeroom',
            name='date_add_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 21, 19, 49, 42, 108050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeroom',
            name='date_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
