# Generated by Django 4.2.2 on 2023-12-21 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_employeeroom_date_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycode',
            name='date_created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 21, 22, 43, 9, 147364, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitycode',
            name='date_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='securitycode',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
