# Generated by Django 4.2.2 on 2024-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0009_securitycode_date_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='rccm_file',
            field=models.ImageField(default='default.png', upload_to='statics/'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='director_card_file',
            field=models.ImageField(default='default_rccm.png', upload_to='statics/'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='statics/'),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_file',
            field=models.FileField(default='default.png', upload_to='statics/'),
        ),
    ]
