# Generated by Django 4.2.2 on 2024-01-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0010_enterprise_rccm_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode', models.CharField(choices=[('Qr code', 'Qr Code'), ('Security code', 'Code de Sécurity'), ('Face', 'Visage')], default='Visage', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.employee')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.enterprise')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.room')),
            ],
        ),
    ]
